FROM golang:1.16-alpine3.12 AS build

RUN apk --update --no-cache add gcc g++ make ca-certificates git tzdata openssh
ENV TZ=Asia/Almaty

WORKDIR /go/src/dta
COPY . .

RUN GOPRIVATE=gitlab.com/adaptive.plus/back/cdp/dta.git
RUN echo "machine gitlab.com login murrboss0 password adm!N08071999" > ~/.netrc && \
     cd cmd/kafka-pipeline && go build main.go

FROM alpine:3.12

RUN apk --update --no-cache add tzdata
ENV TZ=Asia/Almaty

WORKDIR /usr/bin

COPY scylla/ ../scylla/
COPY main .

ENTRYPOINT ["./app"]


Example by Nurlan:

FROM golang:1.17-alpine3.15 AS build
#FROM golang:1.15.3-alpine3.12 AS build
RUN apk --update --no-cache add gcc g++ make ca-certificates git tzdata openssh
ENV TZ=Asia/Almaty
WORKDIR /go/src/project
COPY . .
RUN GOPRIVATE=gitlab.com/adaptive.plus/back/cdp/gds.git
RUN echo “machine gitlab.com login nurlan199206 password glpat-x1U8YUxUBbVdu3Zsphoy” > ~/.netrc && \
  cd cmd/scylla && go build -v
FROM alpine:3.12
RUN apk --update --no-cache add tzdata
ENV TZ=Asia/Almaty
WORKDIR /usr/bin
COPY --from=build /go/src/project/cmd/scylla .
#COPY main .
EXPOSE 7075
ENTRYPOINT [“./scylla”]
CMD [“serve”]

